### PR TITLE
Added dynamic load header of webp library.

### PR DESCRIPTION
**Pull request by fredvs**
Hello.

Added dynamic load header of webp library: libwep_dl.pas.

To load the library use webp_load:

Function webp_load(const libfilename:string) :boolean; 

If libfilename = '' then the library installed in the system will be loaded.
Otherwise it will be the file with path defined by libfilename.

Dont forget to call webp_unload() before to close the application: 

Procedure webp_unload();

### CODE REVIEW

**Comment by circular17** [comment]
Thanks very much

**Comment by circular17** [comment]
I've added a search for the shared library on linux. So that we don't need to provide the so file.

**Comment by fredvs** [comment]
Hello.

If you want to load the library from the system, you do not need to do a search.

Just use `LibWebPLoad('')`   --->  (filename = '').
It will find and load the library him self.

**Comment by fredvs** [comment]
Also I am not sure `FindLinuxLibrary` will be FreeBSD or Mac osx compatible.
If you use LibWebPLoad('') it will work.

**Comment by circular17** [comment]
Nope, I tried and it didn't work. I presume it was looking in the current directory and I removed the so file there for testing.

**Comment by fredvs** [comment]
Hum, it must work.
I will check this now.

**Comment by circular17** [comment]
I suppose it is FreeBSD compatible because ldconfig is there as well. It is not MacOS compatible though.

**Comment by fredvs** [comment]
Hum, indeed, it does not find it.
Strange.
So your `FindLinuxLibrary` is the right solution.

But it disturbs me, with all other dynamic loaders that I use it work.

**Comment by fredvs** [comment]
OK, I get it.

The library installed in the system is `libwebp.so.6`
There is no `libwebp.so` installed.

You may try, change in `libwebp_dl.pas` it will work with this:
```

  {$elseif defined(Linux) or defined(Darwin)}
    LIB_WEBP = 'libwebp.so.6';
  {$else} 
```

**Comment by fredvs** [comment]
One last remark, for Darwin, afaik, the library is called `libwebp.6.dylib`

**Comment by fredvs** [comment]
Very last remark.
Imho it would be better to use the right complete name: libwebp.so.6.
Because the trunk version libweb.so.7 did change parameters of methods and then the Pascal header that we use now will not be compatible with that new future release.

**Comment by circular17** [comment]
Hmm I see. What are those changes? Maybe they are not on the functions we use?

If we link on a specific version, it would not find the library if someone has a newer version?

**Comment by fredvs** [comment]
> If we link on a specific version, it would not find the library if someone has a newer version?

No and it is much better.
I did download + compile +  install the last trunk version of webp.
At installation there is a big warning about some incompatibilities with libwebp.so.6.

But when you do install a library compiled from trunk, usually a link is created, without number, with target the "develop" library.
Here link `libwep.so` target to `libwebp.so.7`

This cause problem if you do not use the so-name with number.
By the way, it is a **big** error of fpc to automatic delete the number of so-name if you use "external" to load a library.

But this is a other story.

So, to resume, it is not a problem because, for sure and for many time, each distro will still provide a libwebp.so.6 because many other apps + libs depend on it.

And when you install the "develop" libwebp.so.7, the old libwebp.so.6 is not deleted. 
[EDIT] And if there is no incompatibilities with previous version, usually distros create link in place of old library :
libwebp.so.6  ----> libwebp.so.7

**Comment by fredvs** [comment]
> Maybe they are not on the functions we use?

Maybe now but it is trunk, it can change.

**Comment by circular17** [comment]
I understand your point of view, that it is safer to specify the exact version to avoid incompatibilities.

There is also another possible point view, I suppose. For example I've tried linking to Python but I had the problem with the library version. When specifying the version, it would not work at all. I had to find on my distro what was the exact version to make it work. But I can't assume all users are going to do that and recompile my software or ask them to set it somewhere in a config file.

By finding the library, we can link it whatever the version or distro. Regarding the changes in the library, I think it is an error to change the signature of widely used functions. A part from an unstable library, it seems to me very shaky to do that, and much better to ensure backward compatibility, for example by adding new flags or new options, or if that doesn't work by adding new functions.

In this point of view, what matters it to have a minimum version. In this case, I know it works with version 6, so this could be the minimum version. Though it may work with an earlier version.

What do you think?

**Comment by fredvs** [comment]
> Regarding the changes in the library, I think it is an error to change the signature of widely used functions. A part from an unstable library, it seems to me very shaky to do that, and much better to ensure backward compatibility, for example by adding new flags or new options, or if that doesn't work by adding new functions.

I wish fpc will follow your advice (last trunk did add parameters to methods that make it unusable with previous version).

But, once again, it is a other story.

> What do you think?

Huh, I prefer to use the complete so name with number of a official stable library for my softwares.
With the header tested for that library.
And if a new stable release appears, I test it and then make the change needed.

But of course do what you feel better, your point of view is perfectly ok.

**Comment by circular17** [comment]
Oh poor fpc bites the dust. But that's another story.

I understand you keep track of version changes and update your software according to it. So you kind of need to publish a new version in some cases. I suppose you would say that anyway it wouldn't be compatible anymore.

On my side, I don't like the idea that programs using BGRABitmap library would need to be update to a new version if the libwebp version changes. Though webp is not so widely used so the impact may not be so major. Also I kind of believe the helper functions provided by libwebp won't change, because they are simple and made to be convenient. So modifying them would be against their primary objective.

I prefer linking whatever the version in this case. Though my point of view is not carved in stone. In particular because I am discovering this subject with libwebgl and libpython.

**Comment by fredvs** [comment]
OK, I understand perfectly your point of view and used it in the past.
But finally it gives me more problems.

And for libwebp, after the warning of trunk installation, I would be prudent...

Anyway, do it like you want, maybe compile + install + test the trunk libwebp.so.7 and if all is ok, you are safe for a long time.

Fre.D

**Comment by circular17** [comment]
I understand your worry after the warning of trunk installation, though looking at the changes I don't see anything happening for the last 4 years on the functions that are used.

The change that I see that may be incompatible is that WebPFree was added during version 5 or something like that. So better put a minimum version 6. I feel it is safe from there.

I think if there are changes, they may be on more low level functions.

Have you some examples of the problems you went into using this strategy in the past?

**Comment by fredvs** [comment]
> Have you some examples of the problems you went into using this strategy in the past?

PortAudio library.
It exists 2 versions: libportaudio.so.8 and libportaudio.so.9.
Some distros give libportaudio.so.8 or/and libportaudio.so.9

Those 2 versions have lot of incompatibilities.

Re-anyway, if you check with minimum version, and if webp-developers do care of their users (not like..., ok, ok no other stories) it should not have any problems.

OK, go on.

Fre;D

**Comment by circular17** [comment]
Hmmm I presume it is an audio library.

Yep, will do.

**Comment by fredvs** [comment]
A other, for graphic, is libfontconfig:
 libfontconfig.so.1 is not compatible with  libfontconfig.so.2.

OK, it was a nice fight, with fast and good result.
I like it.

Thanks Circular.

Fre;D

**Comment by circular17** [comment]
Thanks for your input. Learning new things every day.

For me it is not merely a fight rather a discussion.

I tried a search on google but did not find any detail on those incompatibilities.

**Comment by fredvs** [comment]
> For me it is not merely a fight rather a discussion.

I was talking about my fight to translate the header.


> I tried a search on google but did not find any detail on those incompatibilities.

About what incompatibilities are you refering?
For fontconfig, sorry, it is libfontconfig.so.1 vs libfontconfig.so.2   (not so.2 vs so.3).

**Comment by fredvs** [comment]
> I tried a search on google but did not find any detail on those incompatibilities.

If you are referring to `libwebp.so.7`, here some message after compiling + install the library:


```
...
/usr/bin/ld: warning: libwebp.so.6, needed by /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libtiff.so, may conflict with libwebp.so.7
/usr/bin/ld: warning: libwebp.so.6, needed by /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libtiff.so, may conflict with libwebp.so.7
...
```

But, with your checks, imho, this will not be the case with `BGRABitmap`.
So, sorry for the noise.

Fre;D

**Comment by circular17** [comment]
No worries.

Ok about libtiff and libwebp, that seems to be some dependency thing. But it is rather a generic warning.

> I was talking about my fight to translate the header.

Haha ok well you did a good job.

> About what incompatibilities are you refering?

The ones you encountered with libfontconfig and libportaudio. I don't see how to find information on those problematic changes but I would assume there would be some threads on it online. You're probably not the only person that encountered this. Maybe that's not been documented?

**Comment by fredvs** [comment]
> The ones you encountered with libfontconfig and libportaudio. I don't see how to find information on those problematic changes but I would assume there would be some threads on it online. You're probably not the only person that encountered this. Maybe that's not been documented?

Yes, I know and that is the problem!
You suddenly receive a complain of a user of your library that something does not work, but with your system, it works!

For example, with fpGUI, there was problem with the distro `ArchLinux`.
Finally we discover that ArchLinux install libfontconfig.so.2, all other distro use still libfontconfig.so.1.

But with the fpc feature to cut the "so number" when using "external" and oblige to install the -dev package of the library, with ArchLinux,  `libfontconfig.so` point to ` libfontconfig.so.2` that uses other config files and other methods name.

So the solution to still use static-loading was to... remove that dependency and do a other way!

For `PortAudio` it was nearly the same problem and for `uos`, since that episode, all dependencies are dynamic-loaded and in release is included the binaries of all dependencies, for all OS.
Of course if people prefers to use the libraries of the system, they are free to do it.

And I will not begin with the FreeBSD policy, that keeps the same so-number but suddenly in their new package change name and parameter of some methods without any advises.

All that said, welcome in the happy world of dependencies.

Fre;D

**Pull request merged**
